config/routes.rb
Flix::Application.routes.draw do


  root    "movies#index"
  resources :movies
  get     "movies_all"     =>     "movies#tous" , as: :movies_all
=begin

  get "movies" => "movies#index"
  get "movies/new" => "movies#new",as: "new_movie"

  get "movies/:id" => "movies#show", as: "movie"
  get "movies/:id/edit" => "movies#edit", as: "edit_movie"
  patch "movies/:id" => "movies#update"
=end
end

app/models/movie.rb
class Movie < ActiveRecord::Base

  def flop?
    #total_gross < 500000000
    total_gross.blank? || total_gross < 50000000
  end
  def self.released
    where('released_on<=?', Time.now).order(released_on: :desc)

  end

  def self.hit_movies
    where('total_gross>=?',500000000).order(total_gross: :desc)
  end

  def self.flop_movies
    where('total_gross<?',40000000).order(total_gross: :asc)
  end

  def self.recently_added
  Movie.order(created_at: :desc).limit(3)
  end

  def self.nothing
    where(total_gross: nil)
  end

  def self.tous # affiche tous les films
  Movie.all
  end



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController


  def index
    @movies = Movie.released

  end

  def show
    @movie = Movie.find(params[:id])
  end

  def edit
    @movie = Movie.find(params[:id])
  end



  def update
    # fail
    # Etape 1 : On rapelle les paramètres
    @movie = Movie.find(params[:id])
    # Etape 2 : On autorise les champs sur lesquels on peut transmettre des données à la base de données.
    #movie_params = params[:movie].permit(:title, :description, :rating, :released_on, :total_gross)
#    movie_params = params.require(:movie).permit(:title, :description, :rating, :released_on, :total_gross)

    # Etape 3 : On fait l'update  en fonction de la variable movie_params
    @movie.update(movie_params)
    # Etape 4 : On redirige sur la variable @movie
    redirect_to @movie
    #redirect_to action: "show", id: (params[:id])
    #redirect_to action: "show"
  end

  def new
    @movie = Movie.new
  end

  def create
#    movie_params = params.require(:movie).permit(:title, :description, :rating, :released_on, :total_gross)

    # Etape 3 : On fait l'update  en fonction de la variable movie_params
    @movie= Movie.new(movie_params)
    @movie.save
    # Etape 4 : On redirige sur la variable @movie
    redirect_to @movie
    #redirect_to action: "show", id: (movie_params[:id])
    #redirect_to action: "show"

  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.delete
    redirect_to movies_path
  end

  def tous
    @movies = Movie.tous # va chercher la méthode tous dans movie.rb
    render :index
  end

# existing public methods (actions)
  private

  def movie_params
    params.require(:movie).permit(:title, :description, :rating, :released_on, :total_gross,:cast, :director, :duration, :image_file_name)

  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper

  def format_total_gross(movie)
    if movie.flop?
      content_tag(:strong, 'Flop! ' "#{number_to_currency(movie.total_gross)}")
    else
      content_tag(:strong, 'Hit! ' "#{number_to_currency(movie.total_gross)}")
    end
  end


  def image_for(movie)
    if @routes

      if movie.image_file_name.present? && File.file?("app/assets/images/#{movie.image_file_name}") == true
        image_tag movie.image_file_name, height: '10%', width: '10%'
      elsif movie.image_file_name.blank?
        image_tag('placeholder.png')
      else
        movie.image_file_name.present? && File.file?("app/assets/images/#{movie.image_file_name}") == false
        "Nom Ouii / Fichier Nooon"
      end
    else
      if movie.image_file_name.present? && File.file?("app/assets/images/#{movie.image_file_name}") == true
        image_tag movie.image_file_name, height: '20%', width: '20%'
      elsif movie.image_file_name.blank?
        image_tag('placeholder.png')
      else
        movie.image_file_name.present? && File.file?("app/assets/images/#{movie.image_file_name}") == false
        "Nom Ouii / Fichier Nooon"
      end
    end
  end

  def movietous
    if action_name == 'index'
      pluralize(@movies.count, 'Movie') + " dont la date de sortie est inférieure à aujourdhui, ordonné du plus récent au plus ancien..."
    else
      pluralize(@movies.count, 'Movie') +"Tout les films"
    end
  end


end

app/views/layouts/_aside.html.erb
<aside id="sidebar">
  <nav>
    <ul>
      <li>
        <%= link_to 'All Movies', movies_path %>
      </li>
      <li>
        <%= link_to 'Add New Movie', new_movie_path %>
      </li>
      <li> <%= link_to('Tout afficher', movies_all_path, controller: 'movies', action: 'tous') %>
      </li>
      <li>  <%= link_to('index des films sortis', movies_path, controller: 'movies', action: 'index') %>
      </li>
    </ul>
  </nav>
</aside>

app/views/layouts/_footer.html.erb
<footer id="page-footer">
  <p>
    Copyright &copy; 2014
    <%= link_to 'Simplon', 'http://www.simplon.co' %>
  </p>
</footer>

app/views/layouts/_header.html.erb
<header id="page-header">
  <h1>Super-Heroic Flix</h1>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Les films de Flix</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<%= render "layouts/header" %>
<%= render "layouts/aside" %>

<body>
<%= yield %>
</body>

<%= render "layouts/footer" %>
</html>

app/views/movies/_form.html.erb
<%= form_for (@movie) do |f| %>
    <p>
      <%= f.label :id, 'Identifiant :' %>
      <%= @movie.id %> <br>
      <%= f.label :title, 'Title :' %>
      <%= f.text_field :title, :autofocus => true %>
    </p>
    <p>
      <%= f.label :description %><br/>
      <%= f.text_area :description, cols: 40, rows: 7 %>
    </p>
    <p>
      <%= f.label :rating %><br/>
      <%= f.text_field :rating, size: 5 %>
    </p>
    <p>
      <%= f.label :released_on %><br/>
      <%= f.date_select :released_on %>
      <%= f.date_field :released_on %>
    </p>
    <p>
      <%= f.label :total_gross %><br/>
      <%= f.number_field :total_gross %>
    </p>
    <p>
      <%= f.label :cast %><br/>
      <%= f.text_field :cast %>
    </p>
    <p>
      <%= f.label :director %><br/>
      <%= f.text_field :director %>
    </p>
    <p>
      <%= f.label :duration %><br/>
      <%= f.text_field :duration, size: 10 %>
    </p>
    <p>
      <%= f.label :image_file_name %><br/>
      <%= f.text_field :image_file_name %>

    </p>
    <p>
      <%= f.submit %> <%= button_to 'Cancel', movies_path %>
    </p>
<% end %>

app/views/movies/edit.html.erb
<%= @movie.title %>

<%= render 'movies/form' %>

app/views/movies/index.html.erb
<p>
  <%= movietous %> <!--Si on le lien fait appel à index -> affiche selection de films sinon affiche tout les films -->
</p>

<%= @routes = movies_path %>
<ul>
<% @movies.each do |movie| %>
      <article class="movie">

        <li>

          <%= movie.id %>
        <%= link_to(movie.title, movie) %>
        <%= movie.rating %>
        <%= truncate(movie.description, length: 40, separator: ' ') %>
        <%= movie.released_on %>
        <%# = number_to_currency(movie.total_gross) %>
        <%= format_total_gross(movie) %>
        <%= movie.cast%>
        <%= movie.duration%>
          <%= image_for(movie) %>
        <%= link_to 'Edit', edit_movie_path(movie.id), method: :get %>
      </li>

        <hr>
<% end%>

</ul>

app/views/movies/new.html.erb
<h1>New Film</h1>
<%= render 'movies/form' %>
<%= render 'layouts/footer' %>

app/views/movies/show.html.erb
<%= @movie.title.upcase %>
<%= @movie.rating %>
<%= @movie.description %>
<%= @movie.released_on %>
<%# = number_to_currency(@movie.total_gross) %>
<%= format_total_gross(@movie) %>
<h3>Cast</h3>
<p>
  <%= @movie.cast %>
</p>

<h3>Director</h3>
<p>
  <%= @movie.director %>
</p>

<h3>Duration</h3>
<p>
  <%= @movie.duration %>
</p>

<h3>Image</h3>
<%= image_for(@movie) %>


<nav>
  <%= link_to 'Edit', edit_movie_path(@movie), method: :get %>
  <%= link_to 'Delete', movie_path(@movie), method: :delete, data: {confirm: 'Are you sure?'} %>

</nav>